// server/routes/finetuning.js
const express = require('express');
const router = express.Router();
const fs = require('fs').promises;
const path = require('path');
const axios = require('axios');
const LLMPerformanceLog = require('../models/LLMPerformanceLog');

const { adminAuthMiddleware } = require('../middleware/adminAuthMiddleware');
const { authMiddleware } = require('../middleware/authMiddleware');
const { verifyCallbackSignature } = require('../middleware/verifyCallbackSignature');
const FineTuningEvent = require('../models/FineTuningEvent');
const User = require('../models/User'); // Import User for progress resets

// Define the shared directory path. Ensure this is accessible by both Node.js and Python containers.
const SHARED_DATA_DIR = process.env.SHARED_FINETUNING_DATA_DIR || '/srv/finetuning_data';

// @route   POST /api/admin/finetuning/start
// @desc    Initiates a model fine-tuning job
// @access  Admin
router.post('/start', adminAuthMiddleware, async (req, res) => {
    const { modelIdToUpdate } = req.body;
    if (!modelIdToUpdate) {
        return res.status(400).json({ message: 'modelIdToUpdate is required.' });
    }

    console.log(`[Finetune Orchestrator] Received request to start job for model: ${modelIdToUpdate}`);

    try {
        // Step 1: Collect training data
        let dataset = [];
        let datasetPath = '';
        console.log('[Finetune Orchestrator] Step 1: Checking for training data...');

        const positiveFeedbackLogs = await LLMPerformanceLog.find({ userFeedback: 'positive' })
            .select('query response -_id')
            .lean();

        if (positiveFeedbackLogs.length >= 10) {
            console.log(`[Finetune Orchestrator] Found ${positiveFeedbackLogs.length} positive feedbacks. Using them for training.`);
            dataset = positiveFeedbackLogs.map(log => ({
                instruction: log.query,
                output: log.response
            }));

            await fs.mkdir(SHARED_DATA_DIR, { recursive: true });
            const datasetFilename = `finetuning-dataset-feedback-${Date.now()}.json`;
            datasetPath = path.join(SHARED_DATA_DIR, datasetFilename);
            await fs.writeFile(datasetPath, JSON.stringify(dataset, null, 2));
        } else {
            console.log('[Finetune Orchestrator] Insufficient feedback data. Checking for synthetic datasets...');
            // Check for synthetic datasets generated by qa_generator.py
            const ragDataDir = path.join(__dirname, '..', 'rag_service', 'data', 'training_sets');
            try {
                const files = await fs.readdir(ragDataDir);
                const jsonFiles = files.filter(f => f.endsWith('.json'));

                if (jsonFiles.length > 0) {
                    // Sort by modification time to get the latest
                    const fileStats = await Promise.all(jsonFiles.map(async f => {
                        const stats = await fs.stat(path.join(ragDataDir, f));
                        return { name: f, time: stats.mtime.getTime() };
                    }));
                    fileStats.sort((a, b) => b.time - a.time);

                    const latestDataset = fileStats[0].name;
                    datasetPath = path.join(ragDataDir, latestDataset);
                    const fileContent = await fs.readFile(datasetPath, 'utf8');
                    dataset = JSON.parse(fileContent);
                    console.log(`[Finetune Orchestrator] Using latest synthetic dataset: ${latestDataset} (${dataset.length} pairs)`);
                }
            } catch (err) {
                console.warn(`[Finetune Orchestrator] Could not read synthetic datasets: ${err.message}`);
            }
        }

        if (dataset.length === 0) {
            return res.status(400).json({
                message: 'No training data available. Please generate a Q&A dataset or collect more user feedback.'
            });
        }


        // Step 2: Infer course name for progress resets
        let courseName = 'General';
        if (datasetPath.includes('feedback')) {
            courseName = 'General'; // From logs
        } else {
            // Extract from filename: e.g. "qa_machine_learning.json" -> "machine learning"
            const basename = path.basename(datasetPath, '.json');
            courseName = basename.replace('qa_', '').replace(/_/g, ' ');
            // Capitalize for matching
            courseName = courseName.split(' ').map(s => s.charAt(0).toUpperCase() + s.slice(1)).join(' ');
        }

        // Step 3: Create a FineTuningEvent record
        const jobId = `job_${Date.now()}`;
        const newEvent = new FineTuningEvent({
            jobId,
            modelTagUpdated: modelIdToUpdate.replace('ollama/', ''),
            datasetPath: datasetPath,
            datasetSize: dataset.length,
            courseName: courseName,
            status: 'started'
        });
        await newEvent.save();

        // Step 4: Trigger Python service
        const pythonServiceUrl = process.env.PYTHON_RAG_SERVICE_URL;
        if (pythonServiceUrl) {
            const pythonPayload = {
                job_id: jobId,
                dataset_path: datasetPath,
                model_name_to_update: modelIdToUpdate.replace('ollama/', '')
            };

            axios.post(`${pythonServiceUrl}/finetune`, pythonPayload, { timeout: 5000 })
                .catch(err => console.error(`[Finetune Orchestrator] Python trigger error: ${err.message}`));
        }

        res.status(202).json({
            message: `Fine-tuning job accepted. JobID: ${jobId}`,
            jobId,
            datasetSize: dataset.length
        });

    } catch (error) {
        console.error(`[Finetune Orchestrator] Error: ${error.message}`);
        res.status(500).json({ message: 'Server error during fine-tuning.' });
    }
});

// @route   POST /api/admin/finetuning/update-status
// @desc    Callback for Python service to update job status
router.post('/update-status', verifyCallbackSignature, async (req, res) => {
    const { jobId, status, errorMessage } = req.body;
    console.log(`[Finetune CALLBACK] Status update for ${jobId}: ${status}`);

    try {
        const updateData = { status };
        if (status === 'completed') updateData.completedAt = new Date();
        if (errorMessage) updateData.errorMessage = errorMessage;

        const updatedEvent = await FineTuningEvent.findOneAndUpdate(
            { jobId },
            { $set: updateData },
            { new: true }
        );

        if (!updatedEvent) return res.status(404).json({ message: 'Job not found' });

        if (status === 'completed') {
            const LLMConfiguration = require('../models/LLMConfiguration');
            const modelTag = updatedEvent.modelTagUpdated || 'ai-tutor-custom:latest';

            await LLMConfiguration.findOneAndUpdate(
                { modelId: modelTag, provider: 'ollama' },
                {
                    $set: {
                        modelId: modelTag,
                        provider: 'ollama',
                        displayName: `Specialized Tutor (${modelTag})`,
                        description: "Course-specific model optimized through fine-tuning.",
                        isDefault: false,
                        strengths: ["reasoning", "chat", "technical"]
                    }
                },
                { upsert: true, new: true }
            );
            console.log(`[Finetune CALLBACK] Successfully registered model ${modelTag} in LLMConfiguration.`);

            // --- RESET PROGRESS FOR ALL USERS (Fine-tuning Completed) ---
            if (updatedEvent.courseName) {
                try {
                    const cName = updatedEvent.courseName;
                    const updateObj = {};
                    updateObj[`curriculumProgress.${cName}.quizIndex`] = 0;
                    updateObj[`curriculumProgress.${cName}.quizResults`] = {};

                    const resetResult = await User.updateMany(
                        { [`curriculumProgress.${cName}`]: { $exists: true } },
                        { $set: updateObj }
                    );
                    console.log(`[Finetune] Reset quiz progress for ${resetResult.modifiedCount} users in course: ${cName}`);
                } catch (resetErr) {
                    console.error(`[Finetune] Failed to reset user progress after completion: ${resetErr.message}`);
                }
            }
        }

        res.json({ message: 'Status updated and model registered' });
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
});

// @route   POST /api/admin/finetuning/update-size
// @desc    Callback for Python service to update dataset size (QA Generator)
router.post('/update-size', verifyCallbackSignature, async (req, res) => {
    const { jobId, datasetSize } = req.body;
    try {
        await FineTuningEvent.findOneAndUpdate(
            { jobId },
            { $set: { datasetSize } }
        );
        res.json({ message: 'Size updated' });
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
});


// ─────────────────────────────────────────────────────────────────────────────
// 🎓 ACADEMIC VALIDATION for Quiz/Question Generation
// Mirrors the server-side patterns in chat.js, applied at the data layer.
// ─────────────────────────────────────────────────────────────────────────────
const NON_ACADEMIC_COURSE_PATTERNS = [
    /\b(movies|films|cinema|netflix|series|tv show|web series|anime|drama|episode|season|actor|actress|director|bollywood|hollywood|ott|streaming)\b/i,
    /\b(cricket|football|soccer|basketball|tennis|ipl|fifa|nba|match|score|player|team|tournament|league|gaming|video game|fortnite|pubg|minecraft|gta|valorant|esports)\b/i,
    /\b(instagram|facebook|twitter|tiktok|youtube|snapchat|celebrity|influencer|viral|meme|trending|followers|likes|reels|shorts)\b/i,
    /\b(recipe|cooking|cake|pizza|biryani|restaurant|food|diet|workout|gym|fashion|clothing|style|hair|makeup|skincare)\b/i,
    /\b(gossip|rumor|scandal|affair|breakup|relationship advice|dating|marriage tips|love advice)\b/i,
    /\b(joke|funny|meme|roast|riddle|prank)\b/i,
];

function isCourseAcademic(courseName) {
    if (!courseName) return true; // no course = don't block
    const name = courseName.toLowerCase();

    // Exception for Film Studies / Cinema which are academic
    if (name.includes('syllabus') || name.includes('studies') || name.includes('history') || name.includes('theory')) {
        return true;
    }

    return !NON_ACADEMIC_COURSE_PATTERNS.some(p => p.test(courseName));
}

// @route   GET /api/admin/finetuning/questions
// @desc    Returns QA pairs for a selected course for practice/quiz use.
//          Validates that the selected course is academic before returning data.
// @access  Authenticated users (no admin auth needed — used by AI Assistant mode)
router.get('/questions', authMiddleware, async (req, res) => {
    const { course } = req.query;

    // ── Academic validation ───────────────────────────────────────────────────
    if (course && !isCourseAcademic(course)) {
        console.log(`[Finetuning] 🚫 Non-academic course rejected for quiz: "${course}"`);
        return res.status(422).json({
            success: false,
            isNonAcademic: true,
            course,
            message: `"${course}" is not an academic subject. The AI Practice Quiz only supports academic courses (e.g., Mathematics, Physics, Computer Science, Engineering).`
        });
    }

    try {
        const ragDataDir = path.join(__dirname, '..', 'rag_service', 'data', 'training_sets');

        let files;
        try {
            files = await fs.readdir(ragDataDir);
        } catch {
            return res.json({ success: true, questions: [], message: 'No QA datasets found yet.' });
        }

        const jsonFiles = files.filter(f => f.endsWith('.json'));
        if (jsonFiles.length === 0) {
            return res.json({ success: true, questions: [], message: 'No QA datasets found yet.' });
        }

        // Get metadata (modification time) for all files
        const fileStats = await Promise.all(jsonFiles.map(async f => {
            const stats = await fs.stat(path.join(ragDataDir, f));
            return { name: f, time: stats.mtime.getTime() };
        }));
        fileStats.sort((a, b) => b.time - a.time); // newest first

        // Try to find a course-specific dataset first
        let targetFile = null;
        if (course) {
            const courseSlug = course.toLowerCase().replace(/\s+/g, '_').replace(/[^a-z0-9_]/g, '');
            const courseSpecific = fileStats.find(f =>
                f.name.toLowerCase().includes(courseSlug) ||
                f.name.toLowerCase().includes(course.toLowerCase().replace(/\s+/g, '-'))
            );
            if (courseSpecific) {
                targetFile = courseSpecific;
                console.log(`[Finetuning] Found course-specific dataset for "${course}": ${courseSpecific.name}`);
            }
        }

        // Fall back to latest dataset
        if (!targetFile) {
            targetFile = fileStats[0];
            console.log(`[Finetuning] No course-specific dataset found for "${course || 'unspecified'}". Using latest: ${targetFile.name}`);
        }

        const latestFile = path.join(ragDataDir, targetFile.name);
        const content = await fs.readFile(latestFile, 'utf8');
        const questions = JSON.parse(content);

        res.json({
            success: true,
            questions,
            total: questions.length,
            source: targetFile.name,
            course: course || null
        });
    } catch (err) {
        console.error('[Finetuning] Error reading questions:', err.message);
        res.status(500).json({ success: false, message: 'Failed to load questions.' });
    }
});



module.exports = router;