const log = require('../utils/logger');
// server/workers/adminAnalysisWorker.js
const { workerData, parentPort } = require('worker_threads');
const mongoose = require('mongoose');
const path = require('path');

const AdminDocument = require('../models/AdminDocument');
const connectDB = require('../config/db');
const { ANALYSIS_PROMPTS } = require('../config/promptTemplates');

// Load .env variables from the server directory for the worker
require('dotenv').config({ path: path.resolve(__dirname, '..', '.env') });

const SGLANG_ENABLED = process.env.SGLANG_ENABLED === 'true';

// Use SGLang when available, fall back to Gemini only if explicitly configured
async function callLLM(systemPrompt, userMessage, apiKey) {
    if (SGLANG_ENABLED) {
        const sglangService = require('../services/sglangService');
        const result = await sglangService.generateContentWithHistory([], userMessage, systemPrompt, {
            model: process.env.SGLANG_CHAT_MODEL || 'Qwen/Qwen2.5-7B-Instruct-AWQ',
            ollamaUrl: process.env.SGLANG_CHAT_URL || 'http://localhost:8000/v1',
        });
        return result?.content || result?.message || result;
    }
    // Gemini fallback (only when SGLANG_ENABLED=false)
    const geminiService = require('../services/geminiService');
    const historyForGemini = [{ role: 'user', parts: [{ text: "Perform the requested analysis based on the system instruction and provided document text." }] }];
    return geminiService.generateContentWithHistory(historyForGemini, userMessage, null, { apiKey });
}

async function performAdminDocAnalysis(adminDocumentId, originalName, textForAnalysis) {
    const logPrefix = `[AdminAnalysisWorker ${process.pid}, Doc: ${originalName}]`;
    log.info('DB', `Admin Analysis: Starting (ID: ${adminDocumentId})`);

    const analysisResults = { faq: "", topics: "", mindmap: "" };
    let allIndividualAnalysesSuccessful = true;

    // Key only needed for Gemini fallback path
    const serverApiKey = process.env.GEMINI_API_KEY;
    if (!SGLANG_ENABLED && !serverApiKey) {
        log.error('DB', "FATAL: Server GEMINI_API_KEY not defined and SGLANG_ENABLED=false");
        const errorMessage = "Error generating analysis: No LLM configured.";
        return {
            success: false,
            results: { faq: errorMessage, topics: errorMessage, mindmap: errorMessage },
        };
    }

    async function generateSingleAnalysis(type, promptContentForLLM) {
        try {
            log.info('DB', `Generating ${type}...`);
            const generatedText = await callLLM(null, promptContentForLLM, serverApiKey);

            if (!generatedText || typeof generatedText !== 'string' || generatedText.trim() === "") {
                log.warn('DB', `LLM returned empty content for ${type}`);
                return { success: false, content: `Notice: No content generated by the AI for ${type}.` };
            }
            return { success: true, content: generatedText.trim() };
        } catch (error) {
            log.error('DB', `Error during ${type} generation: ${error.message}`);
            allIndividualAnalysesSuccessful = false;
            return { success: false, content: `Error generating ${type}: ${error.message.split('\\n')[0].substring(0, 250)}` };
        }
    }

    if (!textForAnalysis || textForAnalysis.trim() === "") {
        log.warn('DB', "No text provided for analysis. Skipping.");
        analysisResults.faq = "Skipped: No text content provided.";
        analysisResults.topics = "Skipped: No text content provided.";
        analysisResults.mindmap = "Skipped: No text content provided.";
    } else {
        const analysisPromises = [
            generateSingleAnalysis('FAQ', ANALYSIS_PROMPTS.faq.getPrompt(textForAnalysis)),
            generateSingleAnalysis('Topics', ANALYSIS_PROMPTS.topics.getPrompt(textForAnalysis)),
            generateSingleAnalysis('Mindmap', ANALYSIS_PROMPTS.mindmap.getPrompt(textForAnalysis))
        ];

        const [faqOutcome, topicsOutcome, mindmapOutcome] = await Promise.allSettled(analysisPromises);

        if (faqOutcome.status === 'fulfilled') {
            analysisResults.faq = faqOutcome.value.content;
            if (!faqOutcome.value.success) allIndividualAnalysesSuccessful = false;
        } else {
            analysisResults.faq = `Error generating FAQ: ${faqOutcome.reason?.message?.substring(0,100) || 'Promise rejected'}`;
            allIndividualAnalysesSuccessful = false;
        }

        if (topicsOutcome.status === 'fulfilled') {
            analysisResults.topics = topicsOutcome.value.content;
            if (!topicsOutcome.value.success) allIndividualAnalysesSuccessful = false;
        } else {
            analysisResults.topics = `Error generating Topics: ${topicsOutcome.reason?.message?.substring(0,100) || 'Promise rejected'}`;
            allIndividualAnalysesSuccessful = false;
        }

        if (mindmapOutcome.status === 'fulfilled') {
            analysisResults.mindmap = mindmapOutcome.value.content;
            if (!mindmapOutcome.value.success) allIndividualAnalysesSuccessful = false;
        } else {
            analysisResults.mindmap = `Error generating Mindmap: ${mindmapOutcome.reason?.message?.substring(0,100) || 'Promise rejected'}`;
            allIndividualAnalysesSuccessful = false;
        }
    }
    
    try {
        await AdminDocument.updateOne(
            { _id: adminDocumentId },
            {
                $set: {
                    "analysis.faq": analysisResults.faq,
                    "analysis.topics": analysisResults.topics,
                    "analysis.mindmap": analysisResults.mindmap,
                    "analysisUpdatedAt": new Date()
                }
            }
        );
        // log.info('DB', 'Analysis results stored');
        return { success: allIndividualAnalysesSuccessful, message: `Analysis ${allIndividualAnalysesSuccessful ? 'completed' : 'completed with some failures'}.`, results: analysisResults };
    } catch (dbError) {
        log.error('DB', `DB Error storing analysis: ${dbError.message}`);
        return { success: false, message: `DB Error storing analysis: ${dbError.message}`, results: analysisResults };
    }
}

async function run() {
    // ... (The run function that orchestrates the worker remains the same)
    const { adminDocumentId, originalName, textForAnalysis } = workerData;
    let dbConnected = false;
    let overallTaskSuccess = false;
    let finalMessageToParent = "Admin analysis worker encountered an issue.";

    try {
        await connectDB(process.env.MONGO_URI);
        dbConnected = true;
        const analysisServiceResult = await performAdminDocAnalysis(adminDocumentId, originalName, textForAnalysis);
        overallTaskSuccess = analysisServiceResult.success;
        finalMessageToParent = analysisServiceResult.message;
        if (parentPort) {
            parentPort.postMessage({
                success: overallTaskSuccess,
                originalName: originalName,
                adminDocumentId: adminDocumentId,
                message: finalMessageToParent
            });
        }
    } catch (error) {
        log.error('DB', 'Critical error in worker', error);
        finalMessageToParent = error.message || "Unknown critical error.";
        if (parentPort) {
            parentPort.postMessage({ success: false, originalName, adminDocumentId, error: finalMessageToParent });
        }
    } finally {
        if (dbConnected) {
            await mongoose.disconnect();
        }
        log.success('DB', `Admin analysis task finished (Doc: ${originalName})`);
    }
}

run();