// server/tests/test_offline_question_bank.js
const assert = require('assert');

// 1. Mock Redis Client and Gemini Service before requiring tutor service
const redisConfig = require('../config/redisClient');
const geminiService = require('../services/geminiService');

const mockCourse = "computer-science";
const mockTopicId = "binary-trees";
const mockCacheKey = `im_cache:socratic_precompute:${mockCourse}:${mockTopicId}`;

const mockPrecomputed = {
    intro_summary: "Welcome to Binary Trees! A binary tree is a tree data structure in which each node has at most two children.",
    questions: {
        easy: [
            { question: "What is a binary tree?", expected_answer_nature: "Recall definition of binary tree" },
            { question: "Name two types of binary trees.", expected_answer_nature: "Recall types like full, complete, or balanced" },
            { question: "What is the maximum number of children a binary tree node can have?", expected_answer_nature: "Recall max children is two" }
        ],
        medium: [
            { question: "How would you apply a binary search tree to lookup student records?", expected_answer_nature: "Application of BST lookup" }
        ]
    }
};

let redisStore = {};
redisStore[mockCacheKey] = JSON.stringify(mockPrecomputed);

// Replace the redisClient with a mock client object
redisConfig.redisClient = {
    get: async function (key) {
        return redisStore[key] || null;
    },
    setEx: async function (key, ttl, value) {
        redisStore[key] = value;
        return 'OK';
    }
};

// Track LLM calls
let llmCalled = false;
geminiService.generateContentWithHistory = async function (chatHistory, currentQuery, systemPromptText, options) {
    // Return standard assessment response
    if (systemPromptText && systemPromptText.includes("assessor")) {
        return JSON.stringify({
            understanding: "CORRECT",
            confidence: "HIGH",
            emotionalState: "CURIOUS",
            effortLevel: "HIGH",
            bloom_level: "understand",
            bloomLevel: 2,
            quality: "CORRECT",
            xpMultiplier: 1.1,
            specificGaps: [],
            reasoning: "Correct definition"
        });
    }
    llmCalled = true;
    // Return standard fallback question
    return "This is a fallback question generated by the LLM.";
};

// 2. Import socraticTutorService
const { processTutorResponse, getTutorSessionState, setTutorSessionState } = require('../services/socraticTutorService');

async function runTest() {
    console.log("=== Running Offline Question Bank Unit Test ===");

    const sessionId = "test-session-123";
    const mockLlmConfig = {
        llmProvider: 'gemini',
        apiKey: 'fake-api-key'
    };

    // Setup initial session state
    const initialState = {
        courseName: mockCourse,
        topicId: mockTopicId,
        teachingUnit: "Binary Trees",
        teachingUnitType: "topic",
        turnCount: 0,
        consecutiveCorrect: 0,
        consecutiveWrong: 0,
        hintsGiven: 0,
        masteryScore: 0.0,
        cognitiveLevel: "L1_CONCEPT",
        lastQuestion: "Initial question",
        usedQuestions: [],
        history: []
    };

    await setTutorSessionState(sessionId, initialState);

    // Test Case 1: First follow-up, should pick the first easy precomputed question (index 0)
    console.log("Test Case 1: Picking first precomputed question");
    llmCalled = false;
    let result = await processTutorResponse("A binary tree is a data structure.", sessionId, mockLlmConfig);
    
    assert.ok(result, "Result should not be null.");
    assert.strictEqual(llmCalled, false, "LLM should not be called for question generation when cached questions are available.");
    assert.ok(result.followUpQuestion.includes(mockPrecomputed.questions.easy[0].question), `Should use the first easy question. Got: ${result.followUpQuestion}`);
    
    let updatedState = await getTutorSessionState(sessionId);
    assert.deepStrictEqual(updatedState.usedQuestions, [mockPrecomputed.questions.easy[0].question], "First question should be recorded in usedQuestions.");

    // Test Case 2: Second follow-up, should pick the second easy question (index 1)
    console.log("Test Case 2: Picking second precomputed question");
    llmCalled = false;
    result = await processTutorResponse("Yes, it has nodes.", sessionId, mockLlmConfig);
    
    assert.ok(result, "Result should not be null.");
    assert.strictEqual(llmCalled, false, "LLM should not be called.");
    assert.ok(result.followUpQuestion.includes(mockPrecomputed.questions.easy[1].question), `Should use the second easy question. Got: ${result.followUpQuestion}`);
    
    updatedState = await getTutorSessionState(sessionId);
    assert.ok(updatedState.usedQuestions.includes(mockPrecomputed.questions.easy[1].question), "Second question should be recorded.");

    // Test Case 3: Advanced level - let's force level to medium and see if it picks the medium question
    console.log("Test Case 3: Advancing cognitive level to L2_APPLICATION");
    updatedState.cognitiveLevel = "L2_APPLICATION";
    await setTutorSessionState(sessionId, updatedState);

    llmCalled = false;
    result = await processTutorResponse("Perfect understanding", sessionId, mockLlmConfig);
    assert.ok(result, "Result should not be null.");
    assert.strictEqual(llmCalled, false, "LLM should not be called.");
    assert.ok(result.followUpQuestion.includes(mockPrecomputed.questions.medium[0].question), `Should pick the medium question. Got: ${result.followUpQuestion}`);

    // Test Case 4: Cache exhaustion - requesting L2_APPLICATION again should trigger LLM fallback
    console.log("Test Case 4: Fallback to LLM when level cache is exhausted");
    llmCalled = false;
    
    // We override generateContentWithHistory mock to return a test question
    geminiService.generateContentWithHistory = async function (chatHistory, currentQuery, systemPromptText, options) {
        if (systemPromptText && systemPromptText.includes("assessor")) {
            return JSON.stringify({
                understanding: "CORRECT",
                confidence: "HIGH",
                emotionalState: "CURIOUS",
                effortLevel: "HIGH",
                bloom_level: "understand",
                bloomLevel: 2,
                quality: "CORRECT",
                xpMultiplier: 1.1,
                specificGaps: [],
                reasoning: "Correct definition"
            });
        }
        llmCalled = true;
        return "This is a fallback question generated by the LLM.";
    };

    result = await processTutorResponse("Next answer", sessionId, mockLlmConfig);
    assert.ok(result, "Result should not be null.");
    assert.strictEqual(llmCalled, true, "LLM should be called since there is only 1 precomputed question in the medium bucket.");
    assert.strictEqual(result.followUpQuestion, "This is a fallback question generated by the LLM.", "Should return LLM generated fallback question.");

    console.log("✅ All Offline Question Bank unit tests passed successfully!");
    process.exit(0);
}

runTest().catch(err => {
    console.error("❌ Test failed:", err);
    process.exit(1);
});
